name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: 3.6.0
      - name: Install dependencies
        run: dart pub get
      - name: Run Dart Analyzer
        run: dart format ./ -l 120 --set-exit-if-changed

  analyzer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: 3.6.0
      - name: Install dependencies
        run: dart pub get
      - name: Run Dart Analyzer
        run: dart analyze --fatal-warnings --fatal-infos

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: 3.6.0
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart test
